#!/usr/bin/env node
// Generates the mini program's shared code and data from the web app, so the two
// never drift: recipe library, translations, pure logic modules and the icon set.
//
//   node scripts/sync.mjs          write the generated files
//   node scripts/sync.mjs --check  fail if any generated file is out of date (CI)
//
// Everything written here lands under miniprogram/shared/, miniprogram/data/,
// miniprogram/styles/icons.wxss and packages/tools/links/tools-data.js and is committed, so the project opens in WeChat
// DevTools without running Node first. Do not edit those files by hand.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import * as esbuild from 'esbuild';

const require = createRequire(import.meta.url);
const HERE = path.dirname(fileURLToPath(import.meta.url));
const WEAPP = path.resolve(HERE, '..');
const REPO = path.resolve(WEAPP, '..');
const SRC = path.join(REPO, 'src');
const MP = path.join(WEAPP, 'miniprogram');
const CHECK = process.argv.includes('--check');

const HEADER = '// GENERATED by weapp/scripts/sync.mjs from the web app — do not edit.\n';
const outputs = new Map(); // abs path -> content

function emit(rel, content) {
  outputs.set(path.join(MP, rel), content);
}

// ── ESM module from src/ → CommonJS for the mini program ────────────────────
async function toCjs(entry, { external = [] } = {}) {
  const result = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    write: false,
    format: 'cjs',
    platform: 'neutral',
    target: 'es2017',
    charset: 'utf8',
    legalComments: 'none',
    external,
    logLevel: 'silent',
  });
  return result.outputFiles[0].text;
}

// Modules copied as-is (pure logic / data, no DOM, no React).
const SHARED_MODULES = {
  'shared/calculators.js': 'lib/calculators.js',
  'shared/protocolImport.js': 'lib/protocolImport.js',
  'shared/plateReaderParser.js': 'features/plate/plateReaderParser.js',
  'shared/plateExport.js': 'features/plate/plateExport.js',
  'shared/data.js': 'data/index.js',
  // Only the Links page (tools subpackage) needs this list.
  'packages/tools/links/tools-data.js': 'data/externalTools.js',
};

// ── Recipe library ──────────────────────────────────────────────────────────
// Protocols with brief + detailed steps also carry a legacy `components` list
// that restates the same steps. The web app never shows it for those protocols
// (RecipeDetail hides it), so it is dropped here to keep the main package under
// WeChat's 2 MB limit.
function buildRecipes() {
  const recipes = JSON.parse(fs.readFileSync(path.join(REPO, 'recipes.json'), 'utf8'));
  const slim = recipes.map((r) => {
    if (r.category === 'protocol' && Array.isArray(r.detailedSteps) && r.detailedSteps.length && r.briefSteps) {
      const { components, ...rest } = r; // eslint-disable-line no-unused-vars
      return rest;
    }
    return r;
  });
  // JSON.parse of a string literal is much faster to load than an object literal.
  const literal = JSON.stringify(JSON.stringify(slim))
    .replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
  emit('data/recipes.js', `${HEADER}module.exports = JSON.parse(${literal});\n`);
  return slim.length;
}

// ── Translations ────────────────────────────────────────────────────────────
// Web strings plus mini-program-only strings from weapp/i18n/*.json. Emitted
// twice: a CommonJS module for page logic (toasts, dialogs) and a WXS module so
// templates can call i.t('key', lang) exactly like the web's t(key, lang).
async function buildI18n() {
  const mod = await import(pathToFileURL(path.join(SRC, 'i18n/translations.js')).href);
  const table = { ...mod.translations };
  const i18nDir = path.join(WEAPP, 'i18n');
  const extraFiles = fs.existsSync(i18nDir) ? fs.readdirSync(i18nDir).filter((f) => f.endsWith('.json')).sort() : [];
  const origin = {};
  for (const f of extraFiles) {
    const extra = JSON.parse(fs.readFileSync(path.join(i18nDir, f), 'utf8'));
    for (const [key, val] of Object.entries(extra)) {
      if (origin[key]) throw new Error(`i18n key "${key}" defined in both ${origin[key]} and ${f}`);
      if (!val || typeof val.en !== 'string' || typeof val.zh !== 'string') throw new Error(`i18n key "${key}" in ${f} needs string en + zh`);
      origin[key] = f;
      table[key] = val; // mini-program wording wins over the web's
    }
  }
  const keys = Object.keys(table).sort();
  const compact = {};
  for (const k of keys) {
    const e = table[k] || {};
    const en = typeof e.en === 'string' ? e.en : '';
    // [en] when Chinese is missing or identical; an empty zh is kept — it is a
    // deliberate translation (see t() in src/i18n/index.js).
    compact[k] = typeof e.zh === 'string' && e.zh !== en ? [en, e.zh] : [en];
  }
  const dict = JSON.stringify(compact).replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');

  emit('shared/i18n.js', `${HEADER}const D = ${dict};
const NOTES_EN = ${JSON.stringify(mod.NOTES_EN)};

// t('key', lang) — same contract as the web's i18n t(): a missing translation falls
// back to English; an empty one is deliberate and stays empty.
function t(key, lang) {
  const e = D[key];
  if (!e) return key;
  return lang === 'zh' && e.length > 1 ? e[1] : e[0];
}

// tf('key', lang, { n: 3 }) — t() plus {placeholder} substitution.
function tf(key, lang, params) {
  let s = t(key, lang);
  if (params) Object.keys(params).forEach((p) => { s = s.split('{' + p + '}').join(String(params[p])); });
  return s;
}

function has(key) { return Object.prototype.hasOwnProperty.call(D, key); }

module.exports = { t, tf, has, NOTES_EN };
`);

  // WXS is ES5-only: var, function, no arrow functions or template strings.
  emit('shared/i18n.wxs', `// GENERATED by weapp/scripts/sync.mjs from the web app — do not edit.
var D = ${dict};

function t(key, lang) {
  var e = D[key];
  if (!e) return key;
  return lang === 'zh' && e.length > 1 ? e[1] : e[0];
}

// One {n} placeholder, e.g. i.n('resultsCount', lang, 12)
function n(key, lang, value) {
  return t(key, lang).split('{n}').join('' + value);
}

module.exports = { t: t, n: n };
`);
  return keys.length;
}

// ── Icons ───────────────────────────────────────────────────────────────────
// The web's stroke icons (src/components/icons.jsx) rendered to SVG and used as
// CSS masks: <view class="icon i-star"/> paints in currentColor, so one class
// works in every colour and in dark mode.
async function buildIcons() {
  const bundled = await esbuild.build({
    entryPoints: [path.join(SRC, 'components/icons.jsx')],
    bundle: true, write: false, format: 'cjs', platform: 'node',
    jsx: 'automatic', external: ['react', 'react/jsx-runtime'], logLevel: 'silent',
  });
  const m = { exports: {} };
  new Function('module', 'exports', 'require', bundled.outputFiles[0].text)(m, m.exports, require);
  const React = require('react');
  const { renderToStaticMarkup } = require('react-dom/server');
  const rules = [];
  const names = [];
  for (const [exportName, Comp] of Object.entries(m.exports).sort(([a], [b]) => a.localeCompare(b))) {
    if (!exportName.startsWith('Icon') || typeof Comp !== 'function') continue;
    const variants = [['', {}]];
    if (exportName === 'IconStar') variants.push(['-filled', { filled: true }]);
    for (const [suffix, props] of variants) {
      let svg = renderToStaticMarkup(React.createElement(Comp, { size: 24, ...props }));
      // Masks only use alpha: paint strokes/fills black, add the namespace.
      svg = svg.replace(/currentColor/g, '#000')
        .replace('<svg ', '<svg xmlns="http://www.w3.org/2000/svg" ')
        .replace(/ aria-hidden="true"| focusable="false"/g, '');
      const cls = 'i-' + exportName.slice(4).replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase() + suffix;
      const b64 = Buffer.from(svg).toString('base64');
      rules.push(`.${cls} { -webkit-mask-image: url("data:image/svg+xml;base64,${b64}"); }`);
      names.push(cls);
    }
  }
  emit('styles/icons.wxss', `/* GENERATED by weapp/scripts/sync.mjs from src/components/icons.jsx — do not edit. */
/* Usage: <view class="icon i-star"></view> — sized by font-size, coloured by color. */
.icon {
  display: inline-block;
  flex-shrink: 0;
  width: 1em;
  height: 1em;
  vertical-align: -0.125em;
  background-color: currentColor;
  -webkit-mask-size: 100% 100%;
  -webkit-mask-repeat: no-repeat;
  -webkit-mask-position: center;
}
${rules.join('\n')}
`);
  return names;
}

async function main() {
  for (const [out, src] of Object.entries(SHARED_MODULES)) {
    emit(out, HEADER + await toCjs(path.join(SRC, src)));
  }
  const nRecipes = buildRecipes();
  const nKeys = await buildI18n();
  const icons = await buildIcons();

  let stale = 0;
  for (const [file, content] of outputs) {
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (current === content) continue;
    if (CHECK) {
      console.error('out of date: ' + path.relative(WEAPP, file));
      stale++;
    } else {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, content);
      console.log('wrote ' + path.relative(WEAPP, file));
    }
  }
  if (CHECK && stale) {
    console.error(`\n${stale} generated file(s) out of date — run: npm run sync`);
    process.exit(1);
  }
  console.log(`${nRecipes} recipes · ${nKeys} strings · ${icons.length} icons · ${outputs.size} files ${CHECK ? 'up to date' : 'synced'}`);
}

main().catch((err) => { console.error(err); process.exit(1); });
