// GENERATED by weapp/scripts/sync.mjs from the web app — do not edit.
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// ../src/data/index.js
var index_exports = {};
__export(index_exports, {
  BUFFER_CATEGORIES: () => BUFFER_CATEGORIES,
  CATEGORY_DISPLAY: () => CATEGORY_DISPLAY,
  COMMON_MOLECULES: () => COMMON_MOLECULES,
  ELEMENTS: () => ELEMENTS,
  ELEMENT_BY_SYM: () => ELEMENT_BY_SYM,
  ELEMENT_CAT_COLORS: () => ELEMENT_CAT_COLORS,
  GEL_DEFAULTS: () => GEL_DEFAULTS,
  PLATE_CONFIGS: () => PLATE_CONFIGS,
  PROTOCOL_SUBCATEGORIES: () => PROTOCOL_SUBCATEGORIES,
  PROTOCOL_SUBCAT_BY_ID: () => PROTOCOL_SUBCAT_BY_ID,
  PT_LAYOUT: () => PT_LAYOUT,
  REFERENCES: () => REFERENCES,
  REF_NOTES_EN: () => REF_NOTES_EN,
  ROW_LABELS: () => ROW_LABELS,
  WELL_COLORS: () => WELL_COLORS,
  calcGel: () => calcGel,
  calcMW: () => calcMW,
  parseFormula: () => parseFormula
});
module.exports = __toCommonJS(index_exports);

// ../src/data/periodicTable.js
var ELEMENTS = [
  { z: 1, sym: "H", name: "Hydrogen", mass: 1.008, cat: "nonmetal", econf: "1s¹" },
  { z: 2, sym: "He", name: "Helium", mass: 4.003, cat: "noble-gas", econf: "1s²" },
  { z: 3, sym: "Li", name: "Lithium", mass: 6.941, cat: "alkali", econf: "[He] 2s¹" },
  { z: 4, sym: "Be", name: "Beryllium", mass: 9.012, cat: "alkaline-earth", econf: "[He] 2s²" },
  { z: 5, sym: "B", name: "Boron", mass: 10.81, cat: "metalloid", econf: "[He] 2s² 2p¹" },
  { z: 6, sym: "C", name: "Carbon", mass: 12.011, cat: "nonmetal", econf: "[He] 2s² 2p²" },
  { z: 7, sym: "N", name: "Nitrogen", mass: 14.007, cat: "nonmetal", econf: "[He] 2s² 2p³" },
  { z: 8, sym: "O", name: "Oxygen", mass: 15.999, cat: "nonmetal", econf: "[He] 2s² 2p⁴" },
  { z: 9, sym: "F", name: "Fluorine", mass: 18.998, cat: "halogen", econf: "[He] 2s² 2p⁵" },
  { z: 10, sym: "Ne", name: "Neon", mass: 20.18, cat: "noble-gas", econf: "[He] 2s² 2p⁶" },
  { z: 11, sym: "Na", name: "Sodium", mass: 22.99, cat: "alkali", econf: "[Ne] 3s¹" },
  { z: 12, sym: "Mg", name: "Magnesium", mass: 24.305, cat: "alkaline-earth", econf: "[Ne] 3s²" },
  { z: 13, sym: "Al", name: "Aluminium", mass: 26.982, cat: "post-transition", econf: "[Ne] 3s² 3p¹" },
  { z: 14, sym: "Si", name: "Silicon", mass: 28.086, cat: "metalloid", econf: "[Ne] 3s² 3p²" },
  { z: 15, sym: "P", name: "Phosphorus", mass: 30.974, cat: "nonmetal", econf: "[Ne] 3s² 3p³" },
  { z: 16, sym: "S", name: "Sulfur", mass: 32.065, cat: "nonmetal", econf: "[Ne] 3s² 3p⁴" },
  { z: 17, sym: "Cl", name: "Chlorine", mass: 35.453, cat: "halogen", econf: "[Ne] 3s² 3p⁵" },
  { z: 18, sym: "Ar", name: "Argon", mass: 39.948, cat: "noble-gas", econf: "[Ne] 3s² 3p⁶" },
  { z: 19, sym: "K", name: "Potassium", mass: 39.098, cat: "alkali", econf: "[Ar] 4s¹" },
  { z: 20, sym: "Ca", name: "Calcium", mass: 40.078, cat: "alkaline-earth", econf: "[Ar] 4s²" },
  { z: 21, sym: "Sc", name: "Scandium", mass: 44.956, cat: "transition", econf: "[Ar] 3d¹ 4s²" },
  { z: 22, sym: "Ti", name: "Titanium", mass: 47.867, cat: "transition", econf: "[Ar] 3d² 4s²" },
  { z: 23, sym: "V", name: "Vanadium", mass: 50.942, cat: "transition", econf: "[Ar] 3d³ 4s²" },
  { z: 24, sym: "Cr", name: "Chromium", mass: 51.996, cat: "transition", econf: "[Ar] 3d⁵ 4s¹" },
  { z: 25, sym: "Mn", name: "Manganese", mass: 54.938, cat: "transition", econf: "[Ar] 3d⁵ 4s²" },
  { z: 26, sym: "Fe", name: "Iron", mass: 55.845, cat: "transition", econf: "[Ar] 3d⁶ 4s²" },
  { z: 27, sym: "Co", name: "Cobalt", mass: 58.933, cat: "transition", econf: "[Ar] 3d⁷ 4s²" },
  { z: 28, sym: "Ni", name: "Nickel", mass: 58.693, cat: "transition", econf: "[Ar] 3d⁸ 4s²" },
  { z: 29, sym: "Cu", name: "Copper", mass: 63.546, cat: "transition", econf: "[Ar] 3d¹⁰ 4s¹" },
  { z: 30, sym: "Zn", name: "Zinc", mass: 65.38, cat: "transition", econf: "[Ar] 3d¹⁰ 4s²" },
  { z: 31, sym: "Ga", name: "Gallium", mass: 69.723, cat: "post-transition", econf: "[Ar] 3d¹⁰ 4s² 4p¹" },
  { z: 32, sym: "Ge", name: "Germanium", mass: 72.63, cat: "metalloid", econf: "[Ar] 3d¹⁰ 4s² 4p²" },
  { z: 33, sym: "As", name: "Arsenic", mass: 74.922, cat: "metalloid", econf: "[Ar] 3d¹⁰ 4s² 4p³" },
  { z: 34, sym: "Se", name: "Selenium", mass: 78.971, cat: "nonmetal", econf: "[Ar] 3d¹⁰ 4s² 4p⁴" },
  { z: 35, sym: "Br", name: "Bromine", mass: 79.904, cat: "halogen", econf: "[Ar] 3d¹⁰ 4s² 4p⁵" },
  { z: 36, sym: "Kr", name: "Krypton", mass: 83.798, cat: "noble-gas", econf: "[Ar] 3d¹⁰ 4s² 4p⁶" },
  { z: 37, sym: "Rb", name: "Rubidium", mass: 85.468, cat: "alkali", econf: "[Kr] 5s¹" },
  { z: 38, sym: "Sr", name: "Strontium", mass: 87.62, cat: "alkaline-earth", econf: "[Kr] 5s²" },
  { z: 39, sym: "Y", name: "Yttrium", mass: 88.906, cat: "transition", econf: "[Kr] 4d¹ 5s²" },
  { z: 40, sym: "Zr", name: "Zirconium", mass: 91.224, cat: "transition", econf: "[Kr] 4d² 5s²" },
  { z: 41, sym: "Nb", name: "Niobium", mass: 92.906, cat: "transition", econf: "[Kr] 4d⁴ 5s¹" },
  { z: 42, sym: "Mo", name: "Molybdenum", mass: 95.95, cat: "transition", econf: "[Kr] 4d⁵ 5s¹" },
  { z: 43, sym: "Tc", name: "Technetium", mass: 98, cat: "transition", econf: "[Kr] 4d⁵ 5s²" },
  { z: 44, sym: "Ru", name: "Ruthenium", mass: 101.07, cat: "transition", econf: "[Kr] 4d⁷ 5s¹" },
  { z: 45, sym: "Rh", name: "Rhodium", mass: 102.91, cat: "transition", econf: "[Kr] 4d⁸ 5s¹" },
  { z: 46, sym: "Pd", name: "Palladium", mass: 106.42, cat: "transition", econf: "[Kr] 4d¹⁰" },
  { z: 47, sym: "Ag", name: "Silver", mass: 107.87, cat: "transition", econf: "[Kr] 4d¹⁰ 5s¹" },
  { z: 48, sym: "Cd", name: "Cadmium", mass: 112.41, cat: "transition", econf: "[Kr] 4d¹⁰ 5s²" },
  { z: 49, sym: "In", name: "Indium", mass: 114.82, cat: "post-transition", econf: "[Kr] 4d¹⁰ 5s² 5p¹" },
  { z: 50, sym: "Sn", name: "Tin", mass: 118.71, cat: "post-transition", econf: "[Kr] 4d¹⁰ 5s² 5p²" },
  { z: 51, sym: "Sb", name: "Antimony", mass: 121.76, cat: "metalloid", econf: "[Kr] 4d¹⁰ 5s² 5p³" },
  { z: 52, sym: "Te", name: "Tellurium", mass: 127.6, cat: "metalloid", econf: "[Kr] 4d¹⁰ 5s² 5p⁴" },
  { z: 53, sym: "I", name: "Iodine", mass: 126.9, cat: "halogen", econf: "[Kr] 4d¹⁰ 5s² 5p⁵" },
  { z: 54, sym: "Xe", name: "Xenon", mass: 131.29, cat: "noble-gas", econf: "[Kr] 4d¹⁰ 5s² 5p⁶" },
  { z: 55, sym: "Cs", name: "Caesium", mass: 132.91, cat: "alkali", econf: "[Xe] 6s¹" },
  { z: 56, sym: "Ba", name: "Barium", mass: 137.33, cat: "alkaline-earth", econf: "[Xe] 6s²" },
  { z: 57, sym: "La", name: "Lanthanum", mass: 138.91, cat: "lanthanide", econf: "[Xe] 5d¹ 6s²" },
  { z: 58, sym: "Ce", name: "Cerium", mass: 140.12, cat: "lanthanide", econf: "[Xe] 4f¹ 5d¹ 6s²" },
  { z: 59, sym: "Pr", name: "Praseodymium", mass: 140.91, cat: "lanthanide", econf: "[Xe] 4f³ 6s²" },
  { z: 60, sym: "Nd", name: "Neodymium", mass: 144.24, cat: "lanthanide", econf: "[Xe] 4f⁴ 6s²" },
  { z: 61, sym: "Pm", name: "Promethium", mass: 145, cat: "lanthanide", econf: "[Xe] 4f⁵ 6s²" },
  { z: 62, sym: "Sm", name: "Samarium", mass: 150.36, cat: "lanthanide", econf: "[Xe] 4f⁶ 6s²" },
  { z: 63, sym: "Eu", name: "Europium", mass: 151.96, cat: "lanthanide", econf: "[Xe] 4f⁷ 6s²" },
  { z: 64, sym: "Gd", name: "Gadolinium", mass: 157.25, cat: "lanthanide", econf: "[Xe] 4f⁷ 5d¹ 6s²" },
  { z: 65, sym: "Tb", name: "Terbium", mass: 158.93, cat: "lanthanide", econf: "[Xe] 4f⁹ 6s²" },
  { z: 66, sym: "Dy", name: "Dysprosium", mass: 162.5, cat: "lanthanide", econf: "[Xe] 4f¹⁰ 6s²" },
  { z: 67, sym: "Ho", name: "Holmium", mass: 164.93, cat: "lanthanide", econf: "[Xe] 4f¹¹ 6s²" },
  { z: 68, sym: "Er", name: "Erbium", mass: 167.26, cat: "lanthanide", econf: "[Xe] 4f¹² 6s²" },
  { z: 69, sym: "Tm", name: "Thulium", mass: 168.93, cat: "lanthanide", econf: "[Xe] 4f¹³ 6s²" },
  { z: 70, sym: "Yb", name: "Ytterbium", mass: 173.05, cat: "lanthanide", econf: "[Xe] 4f¹⁴ 6s²" },
  { z: 71, sym: "Lu", name: "Lutetium", mass: 174.97, cat: "lanthanide", econf: "[Xe] 4f¹⁴ 5d¹ 6s²" },
  { z: 72, sym: "Hf", name: "Hafnium", mass: 178.49, cat: "transition", econf: "[Xe] 4f¹⁴ 5d² 6s²" },
  { z: 73, sym: "Ta", name: "Tantalum", mass: 180.95, cat: "transition", econf: "[Xe] 4f¹⁴ 5d³ 6s²" },
  { z: 74, sym: "W", name: "Tungsten", mass: 183.84, cat: "transition", econf: "[Xe] 4f¹⁴ 5d⁴ 6s²" },
  { z: 75, sym: "Re", name: "Rhenium", mass: 186.21, cat: "transition", econf: "[Xe] 4f¹⁴ 5d⁵ 6s²" },
  { z: 76, sym: "Os", name: "Osmium", mass: 190.23, cat: "transition", econf: "[Xe] 4f¹⁴ 5d⁶ 6s²" },
  { z: 77, sym: "Ir", name: "Iridium", mass: 192.22, cat: "transition", econf: "[Xe] 4f¹⁴ 5d⁷ 6s²" },
  { z: 78, sym: "Pt", name: "Platinum", mass: 195.08, cat: "transition", econf: "[Xe] 4f¹⁴ 5d⁹ 6s¹" },
  { z: 79, sym: "Au", name: "Gold", mass: 196.97, cat: "transition", econf: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹" },
  { z: 80, sym: "Hg", name: "Mercury", mass: 200.59, cat: "transition", econf: "[Xe] 4f¹⁴ 5d¹⁰ 6s²" },
  { z: 81, sym: "Tl", name: "Thallium", mass: 204.38, cat: "post-transition", econf: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹" },
  { z: 82, sym: "Pb", name: "Lead", mass: 207.2, cat: "post-transition", econf: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²" },
  { z: 83, sym: "Bi", name: "Bismuth", mass: 208.98, cat: "post-transition", econf: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³" },
  { z: 84, sym: "Po", name: "Polonium", mass: 209, cat: "metalloid", econf: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴" },
  { z: 85, sym: "At", name: "Astatine", mass: 210, cat: "halogen", econf: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵" },
  { z: 86, sym: "Rn", name: "Radon", mass: 222, cat: "noble-gas", econf: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶" },
  { z: 87, sym: "Fr", name: "Francium", mass: 223, cat: "alkali", econf: "[Rn] 7s¹" },
  { z: 88, sym: "Ra", name: "Radium", mass: 226, cat: "alkaline-earth", econf: "[Rn] 7s²" },
  { z: 89, sym: "Ac", name: "Actinium", mass: 227, cat: "actinide", econf: "[Rn] 6d¹ 7s²" },
  { z: 90, sym: "Th", name: "Thorium", mass: 232.04, cat: "actinide", econf: "[Rn] 6d² 7s²" },
  { z: 91, sym: "Pa", name: "Protactinium", mass: 231.04, cat: "actinide", econf: "[Rn] 5f² 6d¹ 7s²" },
  { z: 92, sym: "U", name: "Uranium", mass: 238.03, cat: "actinide", econf: "[Rn] 5f³ 6d¹ 7s²" },
  { z: 93, sym: "Np", name: "Neptunium", mass: 237, cat: "actinide", econf: "[Rn] 5f⁴ 6d¹ 7s²" },
  { z: 94, sym: "Pu", name: "Plutonium", mass: 244, cat: "actinide", econf: "[Rn] 5f⁶ 7s²" },
  { z: 95, sym: "Am", name: "Americium", mass: 243, cat: "actinide", econf: "[Rn] 5f⁷ 7s²" },
  { z: 96, sym: "Cm", name: "Curium", mass: 247, cat: "actinide", econf: "[Rn] 5f⁷ 6d¹ 7s²" },
  { z: 97, sym: "Bk", name: "Berkelium", mass: 247, cat: "actinide", econf: "[Rn] 5f⁹ 7s²" },
  { z: 98, sym: "Cf", name: "Californium", mass: 251, cat: "actinide", econf: "[Rn] 5f¹⁰ 7s²" },
  { z: 99, sym: "Es", name: "Einsteinium", mass: 252, cat: "actinide", econf: "[Rn] 5f¹¹ 7s²" },
  { z: 100, sym: "Fm", name: "Fermium", mass: 257, cat: "actinide", econf: "[Rn] 5f¹² 7s²" },
  { z: 101, sym: "Md", name: "Mendelevium", mass: 258, cat: "actinide", econf: "[Rn] 5f¹³ 7s²" },
  { z: 102, sym: "No", name: "Nobelium", mass: 259, cat: "actinide", econf: "[Rn] 5f¹⁴ 7s²" },
  { z: 103, sym: "Lr", name: "Lawrencium", mass: 266, cat: "actinide", econf: "[Rn] 5f¹⁴ 7s² 7p¹" },
  { z: 104, sym: "Rf", name: "Rutherfordium", mass: 267, cat: "transition", econf: "[Rn] 5f¹⁴ 6d² 7s²" },
  { z: 105, sym: "Db", name: "Dubnium", mass: 268, cat: "transition", econf: "[Rn] 5f¹⁴ 6d³ 7s²" },
  { z: 106, sym: "Sg", name: "Seaborgium", mass: 269, cat: "transition", econf: "[Rn] 5f¹⁴ 6d⁴ 7s²" },
  { z: 107, sym: "Bh", name: "Bohrium", mass: 270, cat: "transition", econf: "[Rn] 5f¹⁴ 6d⁵ 7s²" },
  { z: 108, sym: "Hs", name: "Hassium", mass: 277, cat: "transition", econf: "[Rn] 5f¹⁴ 6d⁶ 7s²" },
  { z: 109, sym: "Mt", name: "Meitnerium", mass: 278, cat: "transition", econf: "[Rn] 5f¹⁴ 6d⁷ 7s²" },
  { z: 110, sym: "Ds", name: "Darmstadtium", mass: 281, cat: "transition", econf: "[Rn] 5f¹⁴ 6d⁸ 7s²" },
  { z: 111, sym: "Rg", name: "Roentgenium", mass: 282, cat: "transition", econf: "[Rn] 5f¹⁴ 6d⁹ 7s²" },
  { z: 112, sym: "Cn", name: "Copernicium", mass: 285, cat: "transition", econf: "[Rn] 5f¹⁴ 6d¹⁰ 7s²" },
  { z: 113, sym: "Nh", name: "Nihonium", mass: 286, cat: "post-transition", econf: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹" },
  { z: 114, sym: "Fl", name: "Flerovium", mass: 289, cat: "post-transition", econf: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²" },
  { z: 115, sym: "Mc", name: "Moscovium", mass: 290, cat: "post-transition", econf: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³" },
  { z: 116, sym: "Lv", name: "Livermorium", mass: 293, cat: "post-transition", econf: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴" },
  { z: 117, sym: "Ts", name: "Tennessine", mass: 294, cat: "halogen", econf: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵" },
  { z: 118, sym: "Og", name: "Oganesson", mass: 294, cat: "noble-gas", econf: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶" }
];
var ELEMENT_BY_SYM = {};
ELEMENTS.forEach((el) => {
  ELEMENT_BY_SYM[el.sym] = el;
});
var ELEMENT_CAT_COLORS = {
  "alkali": "#ff6b6b",
  "alkaline-earth": "#ffa94d",
  "transition": "#4dabf7",
  "post-transition": "#69db7c",
  "metalloid": "#da77f2",
  "nonmetal": "#ffd43b",
  "halogen": "#38d9a9",
  "noble-gas": "#748ffc",
  "lanthanide": "#f783ac",
  "actinide": "#e599f7"
};
var PT_LAYOUT = {
  1: [0, 0],
  2: [0, 17],
  3: [1, 0],
  4: [1, 1],
  5: [1, 12],
  6: [1, 13],
  7: [1, 14],
  8: [1, 15],
  9: [1, 16],
  10: [1, 17],
  11: [2, 0],
  12: [2, 1],
  13: [2, 12],
  14: [2, 13],
  15: [2, 14],
  16: [2, 15],
  17: [2, 16],
  18: [2, 17],
  19: [3, 0],
  20: [3, 1],
  21: [3, 2],
  22: [3, 3],
  23: [3, 4],
  24: [3, 5],
  25: [3, 6],
  26: [3, 7],
  27: [3, 8],
  28: [3, 9],
  29: [3, 10],
  30: [3, 11],
  31: [3, 12],
  32: [3, 13],
  33: [3, 14],
  34: [3, 15],
  35: [3, 16],
  36: [3, 17],
  37: [4, 0],
  38: [4, 1],
  39: [4, 2],
  40: [4, 3],
  41: [4, 4],
  42: [4, 5],
  43: [4, 6],
  44: [4, 7],
  45: [4, 8],
  46: [4, 9],
  47: [4, 10],
  48: [4, 11],
  49: [4, 12],
  50: [4, 13],
  51: [4, 14],
  52: [4, 15],
  53: [4, 16],
  54: [4, 17],
  55: [5, 0],
  56: [5, 1],
  71: [5, 2],
  72: [5, 3],
  73: [5, 4],
  74: [5, 5],
  75: [5, 6],
  76: [5, 7],
  77: [5, 8],
  78: [5, 9],
  79: [5, 10],
  80: [5, 11],
  81: [5, 12],
  82: [5, 13],
  83: [5, 14],
  84: [5, 15],
  85: [5, 16],
  86: [5, 17],
  87: [6, 0],
  88: [6, 1],
  103: [6, 2],
  104: [6, 3],
  105: [6, 4],
  106: [6, 5],
  107: [6, 6],
  108: [6, 7],
  109: [6, 8],
  110: [6, 9],
  111: [6, 10],
  112: [6, 11],
  113: [6, 12],
  114: [6, 13],
  115: [6, 14],
  116: [6, 15],
  117: [6, 16],
  118: [6, 17],
  57: [8, 2],
  58: [8, 3],
  59: [8, 4],
  60: [8, 5],
  61: [8, 6],
  62: [8, 7],
  63: [8, 8],
  64: [8, 9],
  65: [8, 10],
  66: [8, 11],
  67: [8, 12],
  68: [8, 13],
  69: [8, 14],
  70: [8, 15],
  89: [9, 2],
  90: [9, 3],
  91: [9, 4],
  92: [9, 5],
  93: [9, 6],
  94: [9, 7],
  95: [9, 8],
  96: [9, 9],
  97: [9, 10],
  98: [9, 11],
  99: [9, 12],
  100: [9, 13],
  101: [9, 14],
  102: [9, 15]
};
function parseFormula(formula) {
  const sub = { "₀": "0", "₁": "1", "₂": "2", "₃": "3", "₄": "4", "₅": "5", "₆": "6", "₇": "7", "₈": "8", "₉": "9" };
  let f = formula.replace(/[₀-₉]/g, (c) => sub[c] || c);
  function parse(s, i) {
    const counts2 = {};
    while (i < s.length) {
      if (s[i] === "(") {
        const [inner, ni] = parse(s, i + 1);
        i = ni;
        let numStr = "";
        while (i < s.length && /\d/.test(s[i])) {
          numStr += s[i];
          i++;
        }
        const mult = numStr ? parseInt(numStr) : 1;
        for (const el in inner) counts2[el] = (counts2[el] || 0) + inner[el] * mult;
      } else if (s[i] === ")") {
        return [counts2, i + 1];
      } else if (/[A-Z]/.test(s[i])) {
        let sym = s[i];
        i++;
        while (i < s.length && /[a-z]/.test(s[i])) {
          sym += s[i];
          i++;
        }
        let numStr = "";
        while (i < s.length && /\d/.test(s[i])) {
          numStr += s[i];
          i++;
        }
        const n = numStr ? parseInt(numStr) : 1;
        counts2[sym] = (counts2[sym] || 0) + n;
      } else {
        i++;
      }
    }
    return [counts2, i];
  }
  const [counts] = parse(f, 0);
  return counts;
}
function calcMW(formula) {
  const counts = parseFormula(formula);
  let total = 0;
  const breakdown = [];
  for (const sym in counts) {
    const el = ELEMENT_BY_SYM[sym];
    if (!el) return { error: true, sym };
    const sub = el.mass * counts[sym];
    breakdown.push({ sym, name: el.name, count: counts[sym], mass: el.mass, subtotal: sub });
    total += sub;
  }
  return { total, breakdown, error: false };
}
var COMMON_MOLECULES = [
  { name: "NaCl", formula: "NaCl" },
  { name: "KCl", formula: "KCl" },
  { name: "Tris", formula: "C4H11NO3" },
  { name: "EDTA", formula: "C10H16N2O8" },
  { name: "HEPES", formula: "C8H18N2O4S" },
  { name: "SDS", formula: "C12H25NaO4S" },
  { name: "Glycine", formula: "C2H5NO2" },
  { name: "Glucose", formula: "C6H12O6" },
  { name: "Sucrose", formula: "C12H22O11" },
  { name: "CaCl₂", formula: "CaCl2" },
  { name: "MgCl₂", formula: "MgCl2" },
  { name: "Na₂HPO₄", formula: "Na2HPO4" }
];

// ../src/data/gelFormulas.js
var GEL_DEFAULTS = {
  resolving: {
    trisStock: 1.5,
    // M, pH 8.8
    trisVolFrac: 0.25,
    // 25% of total
    sdsVolFrac: 0.01,
    // 1% of 10% SDS stock
    apsVolFrac: 0.01,
    // 1% of 10% APS
    temedPerMl: 6e-4,
    // mL TEMED per mL gel
    acrylamideStock: 30
    // % stock
  },
  stacking: {
    trisStock: 0.5,
    // M, pH 6.8 (or 1.0M with 0.125 vol fraction)
    trisConc: 1,
    // M stock concentration
    trisVolFrac: 0.125,
    // fraction giving 125 mM final
    sdsVolFrac: 0.01,
    apsVolFrac: 0.01,
    temedPerMl: 1e-3,
    acrylamideStock: 30,
    percentage: 4
  }
};
function calcGel(percentage, totalVolume, type = "resolving") {
  const cfg = GEL_DEFAULTS[type];
  const acryVol = percentage / cfg.acrylamideStock * totalVolume;
  let trisVol;
  if (type === "resolving") {
    trisVol = cfg.trisVolFrac * totalVolume;
  } else {
    trisVol = 0.125 / cfg.trisConc * totalVolume;
  }
  const sdsVol = cfg.sdsVolFrac * totalVolume;
  const apsVol = cfg.apsVolFrac * totalVolume;
  const temedVol = cfg.temedPerMl * totalVolume;
  const h2o = totalVolume - acryVol - trisVol - sdsVol - apsVol - temedVol;
  const trisLabel = type === "resolving" ? "1.5 M Tris-HCl pH 8.8" : "1.0 M Tris-HCl pH 6.8";
  return [
    { name: "ddH₂O", vol: Math.max(0, h2o), unit: "mL" },
    { name: `30% Acrylamide/Bis (29:1)`, vol: acryVol, unit: "mL" },
    { name: trisLabel, vol: trisVol, unit: "mL" },
    { name: "10% SDS", vol: sdsVol, unit: "mL" },
    { name: "10% APS (新鲜配制)", vol: apsVol, unit: "mL" },
    { name: "TEMED", vol: temedVol * 1e3, unit: "µL" }
  ];
}

// ../src/data/plateConfigs.js
var PLATE_CONFIGS = {
  6: { rows: 2, cols: 3, wellSize: 56 },
  12: { rows: 3, cols: 4, wellSize: 44 },
  24: { rows: 4, cols: 6, wellSize: 36 },
  48: { rows: 6, cols: 8, wellSize: 28 },
  96: { rows: 8, cols: 12, wellSize: 22 },
  384: { rows: 16, cols: 24, wellSize: 14 }
};
var WELL_COLORS = [
  "#3b82f6",
  "#ef4444",
  "#22c55e",
  "#f59e0b",
  "#8b5cf6",
  "#ec4899",
  "#06b6d4",
  "#f97316",
  "#14b8a6",
  "#6366f1",
  "#a855f7",
  "#84cc16",
  "#e11d48",
  "#0ea5e9",
  "#d946ef",
  "#78716c",
  "#0d9488",
  "#b91c1c",
  "#4338ca",
  "#15803d",
  "#c2410c",
  "#7e22ce",
  "#0369a1",
  "#a16207",
  "#be185d"
];
var ROW_LABELS = "ABCDEFGHIJKLMNOP".split("");

// ../src/data/protocolCategories.js
var BUFFER_CATEGORIES = ["buffer", "staining", "media"];
var PROTOCOL_SUBCATEGORIES = {
  protein: ["wb_protocol", "coip_protocol", "if_protocol", "chip_protocol"],
  nucleic_acid: ["trizol_extraction", "qpcr_protocol", "agarose_gel_electrophoresis", "miniprep_protocol", "colony_pcr", "mycoplasma_pcr"],
  cell_culture: ["trypan_blue_counting", "cell_freezing", "cell_thawing", "cell_transfection", "calcium_phosphate_transfection", "electroporation", "lentivirus_production"],
  cloning: ["heat_shock_transformation", "competent_cells_cacl2", "gibson_assembly", "site_directed_mutagenesis", "colony_pcr", "electroporation"],
  cell_assay: ["mtt_assay", "scratch_assay", "transwell_migration", "flow_cytometry_protocol"]
};
var PROTOCOL_SUBCAT_BY_ID = {};
Object.entries(PROTOCOL_SUBCATEGORIES).forEach(([cat, ids]) => {
  ids.forEach((id) => {
    if (!PROTOCOL_SUBCAT_BY_ID[id]) PROTOCOL_SUBCAT_BY_ID[id] = cat;
  });
});
var CATEGORY_DISPLAY = {
  buffer: { en: "Buffer", zh: "缓冲液" },
  staining: { en: "Staining", zh: "染色" },
  media: { en: "Media", zh: "培养基" },
  protein: { en: "Protein", zh: "蛋白" },
  nucleic_acid: { en: "Nucleic Acid", zh: "核酸" },
  cell_culture: { en: "Cell Culture", zh: "细胞培养" },
  cloning: { en: "Cloning", zh: "克隆" },
  cell_assay: { en: "Cell Assay", zh: "细胞实验" },
  protocol: { en: "Protocol", zh: "实验方案" }
};

// ../src/data/references.js
var REF_NOTES_EN = {
  1: "Foundational SDS-PAGE paper — Laemmli discontinuous electrophoresis system",
  2: "Original Western blot transfer technique paper",
  3: 'Origin of the name "Western blot"',
  4: "Molecular Cloning lab manual (classic reference), contains all buffer recipes",
  5: "Molecular Cloning 4th edition, updated reference manual",
  6: "Detailed SDS-PAGE protocol with gel recipes and staining",
  7: "Original LB medium paper (Lysogeny Broth)",
  8: "SOC medium and high-efficiency transformation protocol",
  9: "Ponceau S staining as WB loading control",
  10: "Gel recipe and operation standards (industry standard)",
  11: "Fast ChIP protocol — Nature Protocols",
  12: "Blue Native PAGE for native protein complexes — Nature Protocols",
  13: "REAP: rapid nuclear/cytoplasmic fractionation",
  14: "TRIzol RNA extraction original paper — >65,000 citations",
  15: "CSH Protocols — standard TRIzol operation",
  16: "MIQE guidelines: minimum information for qPCR publication",
  17: "qPCR 2^(-ΔΔCt) analysis method — >100,000 citations",
  18: "Immunofluorescence staining standard protocol",
  19: "Flow cytometry gold standard guidelines — 500+ pages",
  20: "CRISPR experiment design and analysis review",
  21: "CRISPR RNP delivery protocol",
  22: "His/GST affinity tag protein purification review",
  23: "Complete WB tutorial and troubleshooting",
  24: "MTT cell viability assay original paper",
  25: "ChIP technology review and optimization strategies"
};
var REFERENCES = [
  { id: 1, text: "Laemmli, U. K. (1970). Cleavage of structural proteins during the assembly of the head of bacteriophage T4.", journal: "Nature", vol: "227(5259)", pages: "680–685", doi: "10.1038/227680a0", note: "SDS-PAGE 奠基文献，Laemmli 不连续电泳系统" },
  { id: 2, text: "Towbin, H., Staehelin, T., & Gordon, J. (1979). Electrophoretic transfer of proteins from polyacrylamide gels to nitrocellulose sheets: procedure and some applications.", journal: "PNAS", vol: "76(9)", pages: "4350–4354", doi: "10.1073/pnas.76.9.4350", note: "Western blot 转膜技术原始论文" },
  { id: 3, text: 'Burnette, W. N. (1981). "Western blotting": electrophoretic transfer of proteins from sodium dodecyl sulfate—polyacrylamide gels to unmodified nitrocellulose and radiographic detection with antibody and radioiodinated protein A.', journal: "Analytical Biochemistry", vol: "112(2)", pages: "195–203", doi: "10.1016/0003-2697(81)90281-5", note: '"Western blot" 命名起源' },
  { id: 4, text: "Sambrook, J. & Russell, D. W. (2001). Molecular Cloning: A Laboratory Manual, 3rd edition.", journal: "Cold Spring Harbor Laboratory Press", vol: "", pages: "", doi: "", note: "分子克隆实验手册（经典参考书），含各类 buffer 配方" },
  { id: 5, text: "Green, M. R. & Sambrook, J. (2012). Molecular Cloning: A Laboratory Manual, 4th edition.", journal: "Cold Spring Harbor Laboratory Press", vol: "", pages: "", doi: "", note: "分子克隆第四版，更新版参考手册" },
  { id: 6, text: "Gallagher, S. R. (2012). One-dimensional SDS gel electrophoresis of proteins.", journal: "Current Protocols in Molecular Biology", vol: "Ch.10", pages: "Unit 10.2A", doi: "10.1002/0471142727.mb1002as97", note: "SDS-PAGE 详细实验方案，含胶配方和染色" },
  { id: 7, text: "Bertani, G. (1951). Studies on lysogenesis I: The mode of phage liberation by lysogenic Escherichia coli.", journal: "Journal of Bacteriology", vol: "62(3)", pages: "293–300", doi: "10.1128/jb.62.3.293-300.1951", note: "LB 培养基原始文献 (Lysogeny Broth)" },
  { id: 8, text: "Hanahan, D. (1983). Studies on transformation of Escherichia coli with plasmids.", journal: "Journal of Molecular Biology", vol: "166(4)", pages: "557–580", doi: "10.1016/S0022-2836(83)80284-8", note: "SOC 培养基和高效转化方案" },
  { id: 9, text: "Romero-Calvo, I. et al. (2010). Reversible Ponceau staining as a loading control alternative to actin in Western blots.", journal: "Analytical Biochemistry", vol: "401(2)", pages: "318–320", doi: "10.1016/j.ab.2010.02.036", note: "Ponceau S 染色作为 loading control" },
  { id: 10, text: "Bio-Rad Laboratories. Mini-PROTEAN® Tetra Handcast Systems Instruction Manual.", journal: "Bio-Rad Tech Note", vol: "", pages: "", doi: "", note: "胶配方和操作规范参考 (工业标准)" },
  { id: 11, text: "Nelson, J. D., Denisenko, O. & Bhatt, K. (2006). Protocol for the fast chromatin immunoprecipitation (ChIP) method.", journal: "Nature Protocols", vol: "1(1)", pages: "179–185", doi: "10.1038/nprot.2006.27", note: "ChIP 经典流程 — Nature Protocols" },
  { id: 12, text: "Wittig, I., Braun, H.-P. & Schägger, H. (2006). Blue native PAGE.", journal: "Nature Protocols", vol: "1(1)", pages: "418–428", doi: "10.1038/nprot.2006.62", note: "BN-PAGE 天然蛋白复合物电泳 — Nature Protocols" },
  { id: 13, text: "Suzuki, K., Bose, P., Leong-Quong, R. Y., Fujita, D. J. & Riabowol, K. (2010). REAP: a two minute cell fractionation method.", journal: "BMC Research Notes / Nature Protocols", vol: "5", pages: "532–539", doi: "10.1038/nprot.2009.2", note: "快速核质分离方案" },
  { id: 14, text: "Chomczynski, P. & Sacchi, N. (1987). Single-step method of RNA isolation by acid guanidinium thiocyanate–phenol–chloroform extraction.", journal: "Analytical Biochemistry", vol: "162(1)", pages: "156–159", doi: "10.1016/0003-2697(87)90021-2", note: "TRIzol RNA 提取法原始文献 — 引用量 >65,000" },
  { id: 15, text: "Rio, D. C., Ares, M., Hannon, G. J. & Nilsen, T. W. (2010). Purification of RNA using TRIzol (TRI Reagent).", journal: "Cold Spring Harbor Protocols", vol: "2010(6)", pages: "pdb.prot5439", doi: "10.1101/pdb.prot5439", note: "CSH Protocols — TRIzol 标准操作" },
  { id: 16, text: "Bustin, S. A. et al. (2009). The MIQE guidelines: minimum information for publication of quantitative real-time PCR experiments.", journal: "Clinical Chemistry", vol: "55(4)", pages: "611–622", doi: "10.1373/clinchem.2008.112797", note: "qPCR 实验报告最低信息标准 (MIQE)" },
  { id: 17, text: "Livak, K. J. & Schmittgen, T. D. (2001). Analysis of relative gene expression data using real-time quantitative PCR and the 2^(-ΔΔCt) method.", journal: "Methods", vol: "25(4)", pages: "402–408", doi: "10.1006/meth.2001.1262", note: "qPCR 2^(-ΔΔCt) 分析法 — 引用量 >100,000" },
  { id: 18, text: "Donaldson, J. G. (2015). Immunofluorescence staining.", journal: "Current Protocols in Cell Biology", vol: "69", pages: "4.3.1–4.3.7", doi: "10.1002/0471143030.cb0403s69", note: "免疫荧光标准流程" },
  { id: 19, text: "Cossarizza, A. et al. (2019). Guidelines for the use of flow cytometry and cell sorting in immunological studies (2nd ed.).", journal: "European Journal of Immunology", vol: "49(10)", pages: "1457–1973", doi: "10.1002/eji.201970107", note: "流式细胞术金标准指南 — 500+ 页" },
  { id: 20, text: "Hanna, R. E. & Doench, J. G. (2020). Design and analysis of CRISPR–Cas experiments.", journal: "Nature Biotechnology", vol: "38(7)", pages: "824–844", doi: "10.1038/s41587-020-0490-7", note: "CRISPR 实验设计与分析综述" },
  { id: 21, text: "Kim, S., Kim, D., Cho, S. W., Kim, J. & Kim, J.-S. (2014). Highly efficient RNA-guided genome editing in human cells via delivery of purified Cas9 ribonucleoproteins.", journal: "Genome Research", vol: "24(6)", pages: "1012–1019", doi: "10.1101/gr.171322.113", note: "CRISPR RNP 递送方案" },
  { id: 22, text: "Kimple, M. E., Brill, A. L. & Pasker, R. L. (2013). Overview of affinity tags for protein purification.", journal: "Current Protocols in Protein Science", vol: "73", pages: "9.9.1–9.9.23", doi: "10.1002/0471140864.ps0909s73", note: "His/GST 等亲和标签蛋白纯化综述" },
  { id: 23, text: "Mahmood, T. & Yang, P.-C. (2012). Western blot: technique, theory, and trouble shooting.", journal: "North American Journal of Medical Sciences", vol: "4(9)", pages: "429–434", doi: "10.4103/1947-2714.100998", note: "WB 完整教程与 troubleshooting" },
  { id: 24, text: "Mosmann, T. (1983). Rapid colorimetric assay for cellular growth and survival.", journal: "Journal of Immunological Methods", vol: "65(1-2)", pages: "55–63", doi: "10.1016/0022-1759(83)90303-4", note: "MTT 细胞活力检测原始文献" },
  { id: 25, text: "Collas, P. (2010). The current state of chromatin immunoprecipitation.", journal: "Molecular Biotechnology", vol: "45(1)", pages: "87–100", doi: "10.1007/s12033-009-9239-8", note: "ChIP 技术综述与优化策略" }
];
