// GENERATED by weapp/scripts/sync.mjs from the web app — do not edit.
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// ../src/lib/ics.js
var ics_exports = {};
__export(ics_exports, {
  buildICS: () => buildICS,
  experimentSpan: () => experimentSpan,
  icsEntries: () => icsEntries,
  icsEscape: () => icsEscape,
  icsFold: () => icsFold
});
module.exports = __toCommonJS(ics_exports);
var pad2 = (n) => String(n).padStart(2, "0");
var DATE_RE = /^(\d{4})-(\d{2})-(\d{2})$/;
var TIME_RE = /^(\d{1,2}):(\d{2})$/;
function icsEntries(entries, from, to) {
  const end = to || "9999-12-31";
  return (entries || []).filter((e) => e && e.date && e.date >= (from || "") && e.date <= end);
}
function icsEscape(value) {
  return String(value != null ? value : "").replace(/\\/g, "\\\\").replace(/;/g, "\\;").replace(/,/g, "\\,").replace(/\r\n|\r|\n/g, "\\n");
}
function icsFold(line) {
  const out = [];
  let cur = "";
  let bytes = 0;
  for (const ch of line) {
    const cp = ch.codePointAt(0);
    const len = cp < 128 ? 1 : cp < 2048 ? 2 : cp < 65536 ? 3 : 4;
    const limit = out.length ? 74 : 75;
    if (bytes + len > limit) {
      out.push(cur);
      cur = "";
      bytes = 0;
    }
    cur += ch;
    bytes += len;
  }
  out.push(cur);
  return out.join("\r\n ");
}
function stampLocal(d) {
  return `${d.getFullYear()}${pad2(d.getMonth() + 1)}${pad2(d.getDate())}T${pad2(d.getHours())}${pad2(d.getMinutes())}00`;
}
function stampUTC(d) {
  return `${d.getUTCFullYear()}${pad2(d.getUTCMonth() + 1)}${pad2(d.getUTCDate())}T${pad2(d.getUTCHours())}${pad2(d.getUTCMinutes())}${pad2(d.getUTCSeconds())}Z`;
}
function experimentSpan(e) {
  const dm = DATE_RE.exec((e == null ? void 0 : e.date) || "");
  if (!dm) return null;
  const tm = TIME_RE.exec(e.startTime || "");
  const timeOk = !!tm && +tm[1] < 24 && +tm[2] < 60;
  const start = new Date(+dm[1], +dm[2] - 1, +dm[3], timeOk ? +tm[1] : 9, timeOk ? +tm[2] : 0);
  const dur = Number(e.duration);
  const minutes = Number.isFinite(dur) && dur > 0 ? dur : 60;
  return { start, end: new Date(start.getTime() + minutes * 6e4) };
}
function buildICS(entries, { now = /* @__PURE__ */ new Date() } = {}) {
  var _a;
  const lines = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//bioinfospace labmate//EN", "CALSCALE:GREGORIAN"];
  const dtstamp = stampUTC(now);
  for (const e of entries || []) {
    const span = experimentSpan(e);
    if (!span) continue;
    lines.push("BEGIN:VEVENT");
    lines.push(`UID:${e.id}@labmate.bioinfospace.com`);
    lines.push(`DTSTAMP:${dtstamp}`);
    lines.push(`DTSTART:${stampLocal(span.start)}`);
    lines.push(`DTEND:${stampLocal(span.end)}`);
    lines.push(`SUMMARY:${icsEscape(e.title || e.titleZh || "Experiment")}`);
    if ((_a = e.plan) == null ? void 0 : _a.objectives) lines.push(`DESCRIPTION:${icsEscape(e.plan.objectives)}`);
    lines.push(`STATUS:${e.status === "completed" ? "CONFIRMED" : e.status === "cancelled" ? "CANCELLED" : "TENTATIVE"}`);
    lines.push("END:VEVENT");
  }
  lines.push("END:VCALENDAR");
  return lines.map(icsFold).join("\r\n") + "\r\n";
}
