// GENERATED by weapp/scripts/sync.mjs from the web app — do not edit.
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// ../src/features/plate/plateState.js
var plateState_exports = {};
__export(plateState_exports, {
  PLATE_STORE_KEY: () => PLATE_STORE_KEY,
  loadPlateState: () => loadPlateState,
  toStoredPlate: () => toStoredPlate
});
module.exports = __toCommonJS(plateState_exports);

// ../src/data/plateConfigs.js
var PLATE_CONFIGS = {
  6: { rows: 2, cols: 3, wellSize: 56 },
  12: { rows: 3, cols: 4, wellSize: 44 },
  24: { rows: 4, cols: 6, wellSize: 36 },
  48: { rows: 6, cols: 8, wellSize: 28 },
  96: { rows: 8, cols: 12, wellSize: 22 },
  384: { rows: 16, cols: 24, wellSize: 14 }
};
var WELL_COLORS = [
  "#3b82f6",
  "#ef4444",
  "#22c55e",
  "#f59e0b",
  "#8b5cf6",
  "#ec4899",
  "#06b6d4",
  "#f97316",
  "#14b8a6",
  "#6366f1",
  "#a855f7",
  "#84cc16",
  "#e11d48",
  "#0ea5e9",
  "#d946ef",
  "#78716c",
  "#0d9488",
  "#b91c1c",
  "#4338ca",
  "#15803d",
  "#c2410c",
  "#7e22ce",
  "#0369a1",
  "#a16207",
  "#be185d"
];
var ROW_LABELS = "ABCDEFGHIJKLMNOP".split("");

// ../src/features/plate/plateState.js
var PLATE_STORE_KEY = "labmate_plate";
var DEFAULT_TYPE = 96;
var COLOR_RE = /^(#[0-9a-f]{3,8}|[a-z]+|(rgb|hsl)a?\([\d\s.,%]+\))$/i;
var HEX6_RE = /^#[0-9a-f]{6}$/i;
var safeColor = (c) => COLOR_RE.test(String(c || "")) ? String(c) : WELL_COLORS[0];
function parseWellKey(key) {
  const r = ROW_LABELS.indexOf(String(key).charAt(0));
  const c = parseInt(String(key).slice(1), 10) - 1;
  return r >= 0 && c >= 0 ? { r, c } : null;
}
function loadPlateState(raw) {
  const s = raw && typeof raw === "object" ? raw : {};
  const plateType = PLATE_CONFIGS[s.plateType] ? Number(s.plateType) : DEFAULT_TYPE;
  const cfg = PLATE_CONFIGS[plateType];
  const wellData = {};
  if (s.wellData && typeof s.wellData === "object") {
    Object.keys(s.wellData).forEach((key) => {
      const pos = parseWellKey(key);
      const d = s.wellData[key];
      if (!pos || pos.r >= cfg.rows || pos.c >= cfg.cols || !d || typeof d !== "object") return;
      wellData[ROW_LABELS[pos.r] + (pos.c + 1)] = { color: safeColor(d.color), label: d.label == null ? "" : String(d.label) };
    });
  }
  const groups = (Array.isArray(s.groups) ? s.groups : []).filter((g) => g && Array.isArray(g.wells)).map((g) => ({
    label: g.label == null ? "" : String(g.label),
    color: safeColor(g.color),
    wells: g.wells.map(String).filter((w) => wellData[w])
  })).filter((g) => g.wells.length > 0);
  return {
    plateType,
    wellData,
    groups,
    colorIdx: Number.isInteger(s.colorIdx) && s.colorIdx >= 0 ? s.colorIdx % WELL_COLORS.length : 0,
    useCustom: !!s.useCustom,
    customColor: HEX6_RE.test(s.customColor) ? s.customColor : "#ff0000"
  };
}
function toStoredPlate({ plateType, wellData, groups, colorIdx, useCustom, customColor }) {
  const empty = !wellData || Object.keys(wellData).length === 0;
  if (empty && Number(plateType) === DEFAULT_TYPE && !useCustom) return null;
  return {
    plateType: Number(plateType),
    wellData: wellData || {},
    groups: groups || [],
    colorIdx: ((Number(colorIdx) || 0) % WELL_COLORS.length + WELL_COLORS.length) % WELL_COLORS.length,
    useCustom: !!useCustom,
    customColor: customColor || "#ff0000"
  };
}
