// GENERATED by weapp/scripts/sync.mjs from the web app — do not edit.
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// ../src/features/plate/plateReaderParser.js
var plateReaderParser_exports = {};
__export(plateReaderParser_exports, {
  longFormatToCSV: () => longFormatToCSV,
  parseNum: () => parseNum,
  parsePlateReaderCSV: () => parsePlateReaderCSV,
  summarizeBySample: () => summarizeBySample,
  toLongFormat: () => toLongFormat
});
module.exports = __toCommonJS(plateReaderParser_exports);

// ../src/data/plateConfigs.js
var PLATE_CONFIGS = {
  6: { rows: 2, cols: 3, wellSize: 56 },
  12: { rows: 3, cols: 4, wellSize: 44 },
  24: { rows: 4, cols: 6, wellSize: 36 },
  48: { rows: 6, cols: 8, wellSize: 28 },
  96: { rows: 8, cols: 12, wellSize: 22 },
  384: { rows: 16, cols: 24, wellSize: 14 }
};
var ROW_LABELS = "ABCDEFGHIJKLMNOP".split("");

// ../src/features/plate/plateReaderParser.js
var PLATE_DIMS = Object.entries(PLATE_CONFIGS).map(([size, cfg]) => ({ size: Number(size), rows: cfg.rows, cols: cfg.cols })).sort((a, b) => a.size - b.size);
function detectSeparator(text) {
  const sample = text.split(/\r?\n/).slice(0, 20).join("\n");
  const counts = {
    "	": (sample.match(/\t/g) || []).length,
    ",": (sample.match(/,/g) || []).length,
    ";": (sample.match(/;/g) || []).length
  };
  return Object.entries(counts).sort((a, b) => b[1] - a[1])[0][0];
}
function parseNum(s) {
  if (s == null) return null;
  const t = String(s).trim();
  if (!t) return null;
  const m = t.replace(/[<>]/g, "").match(/-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?/);
  if (!m) return null;
  const n = parseFloat(m[0]);
  return Number.isFinite(n) ? n : null;
}
function isHeaderRow(cells, expectedCols) {
  let i = 0;
  while (i < cells.length && !String(cells[i]).trim()) i++;
  const trimmed = cells.slice(i).map((c) => String(c).trim());
  if (trimmed.length < expectedCols) return false;
  let hits = 0;
  for (let k = 0; k < expectedCols; k++) {
    const m = trimmed[k].match(/^(?:col(?:umn)?\s*)?(\d+)$/i);
    if (m && parseInt(m[1], 10) === k + 1) hits++;
  }
  return hits >= Math.max(2, expectedCols - 1);
}
function looksLikeColumnHeader(cells) {
  if (cells.length < 4) return false;
  const first = String(cells[0]).trim();
  if (first !== "" && /^[A-P]$/i.test(first)) return false;
  if (first !== "" && parseNum(first) !== null) return false;
  const tail = cells.slice(1).map((c) => String(c).trim());
  if (tail.length < 3) return false;
  let hits = 0;
  for (let k = 0; k < tail.length; k++) {
    const m = tail[k].match(/^(?:col(?:umn)?\s*)?(\d+)$/i);
    if (m && parseInt(m[1], 10) === k + 1) hits++;
  }
  return hits >= tail.length - 1;
}
function isHeaderColumn(rows, start, n) {
  var _a;
  let alphaHits = 0;
  let numHits = 0;
  for (let r = 0; r < n; r++) {
    const cell = String(((_a = rows[start + r]) == null ? void 0 : _a[0]) || "").trim();
    if (/^[A-P]$/i.test(cell) && cell.toUpperCase() === ROW_LABELS[r]) alphaHits++;
    else if (parseInt(cell, 10) === r + 1) numHits++;
  }
  return alphaHits >= Math.max(2, n - 1) || numHits >= Math.max(2, n - 1);
}
function parsePlateReaderCSV(text) {
  if (!text || !text.trim()) {
    return { error: "empty", values: {}, plateSize: 0, rows: 0, cols: 0, parsed: 0, unparsed: 0 };
  }
  const sep = detectSeparator(text);
  const rows = text.split(/\r?\n/).map((line) => line.split(sep).map((c) => c.trim())).filter((row) => row.some((c) => c !== ""));
  if (rows.length === 0) {
    return { error: "no_data", values: {}, plateSize: 0, rows: 0, cols: 0, parsed: 0, unparsed: 0 };
  }
  const isDataRow = rows.map((row) => {
    if (row.length < 2) return false;
    const nums = row.filter((c) => parseNum(c) !== null).length;
    return nums / row.length >= 0.4 && nums >= 2;
  });
  let bestStart = -1;
  let bestLen = 0;
  let curStart = -1;
  let curLen = 0;
  for (let i = 0; i < rows.length; i++) {
    if (isDataRow[i]) {
      if (curStart === -1) curStart = i;
      curLen++;
      if (curLen > bestLen) {
        bestStart = curStart;
        bestLen = curLen;
      }
    } else {
      curStart = -1;
      curLen = 0;
    }
  }
  if (bestLen === 0) {
    return { error: "no_numeric_block", values: {}, plateSize: 0, rows: 0, cols: 0, parsed: 0, unparsed: 0 };
  }
  let headerRowSeen = false;
  while (bestLen > 1 && looksLikeColumnHeader(rows[bestStart])) {
    bestStart++;
    bestLen--;
    headerRowSeen = true;
  }
  const widths = rows.slice(bestStart, bestStart + bestLen).map((r) => r.length);
  const widthCounts = widths.reduce((acc, w) => {
    acc[w] = (acc[w] || 0) + 1;
    return acc;
  }, {});
  const dataWidth = Number(Object.entries(widthCounts).sort((a, b) => b[1] - a[1])[0][0]);
  const hasHeaderCol = isHeaderColumn(rows, bestStart, bestLen);
  const colOffset = hasHeaderCol ? 1 : 0;
  const valueCols = dataWidth - colOffset;
  const candidate = PLATE_DIMS.find((p) => p.cols === valueCols && p.rows === bestLen) || PLATE_DIMS.find((p) => p.cols === valueCols) || PLATE_DIMS.find((p) => p.rows === bestLen);
  if (!candidate) {
    return {
      error: "unknown_plate_size",
      values: {},
      plateSize: 0,
      rows: bestLen,
      cols: valueCols,
      parsed: 0,
      unparsed: 0
    };
  }
  const hasHeaderRow = headerRowSeen || bestStart > 0 && isHeaderRow(rows[bestStart - 1], candidate.cols);
  const finalRows = Math.min(bestLen, candidate.rows);
  const finalCols = Math.min(valueCols, candidate.cols);
  const values = {};
  let parsed = 0;
  let unparsed = 0;
  for (let r = 0; r < finalRows; r++) {
    const row = rows[bestStart + r];
    for (let c = 0; c < finalCols; c++) {
      const raw = row[c + colOffset];
      const v = parseNum(raw);
      const key = ROW_LABELS[r] + (c + 1);
      if (v !== null) {
        values[key] = v;
        parsed++;
      } else if (raw !== void 0 && raw !== "") {
        unparsed++;
      }
    }
  }
  return {
    plateSize: candidate.size,
    rows: candidate.rows,
    cols: candidate.cols,
    values,
    parsed,
    unparsed,
    hasHeaderRow,
    hasHeaderCol,
    separator: sep
  };
}
function toLongFormat(parsed, wellData) {
  const out = [];
  Object.entries(parsed.values).forEach(([well, value]) => {
    const rowLetter = well.charAt(0);
    const col = parseInt(well.slice(1), 10);
    const row = ROW_LABELS.indexOf(rowLetter) + 1;
    const layout = wellData ? wellData[well] : null;
    out.push({
      well,
      rowLabel: rowLetter,
      row,
      col,
      value,
      sample: (layout == null ? void 0 : layout.label) || "",
      color: (layout == null ? void 0 : layout.color) || ""
    });
  });
  return out.sort((a, b) => {
    if (a.rowLabel !== b.rowLabel) return a.rowLabel.localeCompare(b.rowLabel);
    return a.col - b.col;
  });
}
function longFormatToCSV(rows, opts = {}) {
  const includeSample = opts.includeSample !== false;
  const headers = ["well", "row", "col", "value"];
  if (includeSample) headers.push("sample");
  const lines = [headers.join(",")];
  for (const r of rows) {
    const cells = [r.well, r.rowLabel, r.col, r.value];
    if (includeSample) {
      const s = (r.sample || "").replace(/"/g, '""');
      cells.push(s.includes(",") || s.includes('"') ? `"${s}"` : s);
    }
    lines.push(cells.join(","));
  }
  return lines.join("\n") + "\n";
}
function summarizeBySample(longRows) {
  const groups = {};
  for (const r of longRows) {
    if (!r.sample) continue;
    if (!groups[r.sample]) groups[r.sample] = { sample: r.sample, color: r.color, values: [], wells: [] };
    groups[r.sample].values.push(r.value);
    groups[r.sample].wells.push(r.well);
  }
  return Object.values(groups).map((g) => {
    const n = g.values.length;
    const mean = g.values.reduce((s, v) => s + v, 0) / n;
    const variance = n > 1 ? g.values.reduce((s, v) => s + (v - mean) ** 2, 0) / (n - 1) : 0;
    const sd = Math.sqrt(variance);
    return { sample: g.sample, color: g.color, n, mean, sd, sem: n > 1 ? sd / Math.sqrt(n) : 0, wells: g.wells };
  }).sort((a, b) => a.sample.localeCompare(b.sample));
}
