// GENERATED by weapp/scripts/sync.mjs from the web app — do not edit.
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// ../src/lib/protocolImport.js
var protocolImport_exports = {};
__export(protocolImport_exports, {
  normalizeProtocolSteps: () => normalizeProtocolSteps,
  recipeTitle: () => recipeTitle,
  toProcedureSteps: () => toProcedureSteps,
  toReagents: () => toReagents
});
module.exports = __toCommonJS(protocolImport_exports);
function stepText(step, lang) {
  if (step == null) return "";
  if (typeof step === "string") return step;
  return step[lang] || step.en || step.zh || step.text || step.step || "";
}
function normalizeProtocolSteps(recipe, lang = "en") {
  if (!recipe) return [];
  const detailed = Array.isArray(recipe.detailedSteps) ? recipe.detailedSteps : [];
  const actionSteps = detailed.filter((s) => typeof s === "string" || !s.isHeader);
  const source = actionSteps.length > 0 ? actionSteps : Array.isArray(recipe.briefSteps) ? recipe.briefSteps : [];
  return source.map((s) => stepText(s, lang)).filter((t) => t.trim().length > 0);
}
function toProcedureSteps(recipe, lang = "en") {
  return normalizeProtocolSteps(recipe, lang).map((text) => ({
    stepText: text,
    completed: false,
    deviation: "",
    actualParams: ""
  }));
}
function toReagents(recipe) {
  const materials = Array.isArray(recipe == null ? void 0 : recipe.materials) ? recipe.materials : [];
  return materials.map((m) => ({
    name: typeof m === "string" ? m : m.name || m.reagent || "",
    amount: m && m.amount || "",
    unit: m && m.unit || "",
    location: "",
    inventoryRef: null
  }));
}
function recipeTitle(recipe, lang = "en") {
  if (!recipe) return "";
  return lang === "zh" ? recipe.nameCn || recipe.name || "" : recipe.name || "";
}
