// GENERATED by weapp/scripts/sync.mjs from the web app — do not edit.
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// ../src/data/externalTools.js
var externalTools_exports = {};
__export(externalTools_exports, {
  EXTERNAL_TOOLS: () => EXTERNAL_TOOLS
});
module.exports = __toCommonJS(externalTools_exports);
var EXTERNAL_TOOLS = [
  { cat: "toolCatBIS", tools: [
    { name: "ELISA Calculator", url: "https://apps.bioinfospace.com/ELISA_calculator/", desc: { en: "Standard curve fitting & concentration calculation", zh: "标准曲线拟合 & 浓度计算" } },
    { name: "qPCR Analyzer", url: "https://apps.bioinfospace.com/qpcr-analysis/", desc: { en: "ΔΔCt analysis & expression plots", zh: "ΔΔCt 分析 & 表达量图" } },
    { name: "freeCount", url: "https://apps.bioinfospace.com/freeCount/", desc: { en: "Differential expression analysis (DESeq2/edgeR)", zh: "差异表达分析 (DESeq2/edgeR)" } },
    { name: "crispRdesignR", url: "https://apps.bioinfospace.com/crispRdesignR/", desc: { en: "CRISPR sgRNA design & off-target scoring", zh: "CRISPR sgRNA 设计 & 脱靶评分" } },
    { name: "JBrowse 2", url: "https://apps.bioinfospace.com/jbrowse/", desc: { en: "Genome browser with custom tracks", zh: "基因组浏览器（自定义 track）" } }
  ] },
  { cat: "toolCatPrimer", tools: [
    { name: "PrimerBank", abbr: "PR", url: "https://pga.mgh.harvard.edu/primerbank/", desc: { en: "Pre-validated qPCR primers by gene", zh: "按基因查找已验证 qPCR 引物" } },
    { name: "Primer-BLAST", url: "https://www.ncbi.nlm.nih.gov/tools/primer-blast/", desc: { en: "Design primers with specificity check", zh: "设计引物 + 特异性检查" } },
    { name: "BLAST", url: "https://blast.ncbi.nlm.nih.gov/", desc: { en: "Sequence alignment & identity search", zh: "序列比对 & 同源搜索" } },
    { name: "NEB Tm Calculator", url: "https://tmcalculator.neb.com/", desc: { en: "Accurate Tm with salt/primer concentration", zh: "精确 Tm（考虑盐浓度和引物浓度）" } },
    { name: "SnapGene Viewer", url: "https://www.snapgene.com/snapgene-viewer", desc: { en: "Free plasmid map viewer", zh: "免费质粒图谱查看器" } },
    { name: "NEBcutter", abbr: "NC", url: "https://nc3.neb.com/NEBcutter/", desc: { en: "Restriction enzyme site analysis", zh: "限制性内切酶位点分析" } }
  ] },
  { cat: "toolCatProtein", tools: [
    { name: "UniProt", url: "https://www.uniprot.org/", desc: { en: "Protein function, domains & sequences", zh: "蛋白功能、结构域 & 序列" } },
    { name: "ExPASy ProtParam", url: "https://web.expasy.org/protparam/", desc: { en: "MW, pI, extinction coefficient", zh: "分子量、等电点、消光系数" } },
    { name: "CiteAb", url: "https://www.citeab.com/", desc: { en: "Antibody citation data & validation", zh: "抗体引用数据 & 验证信息" } },
    { name: "Addgene", url: "https://www.addgene.org/", desc: { en: "Plasmid repository & viral vectors", zh: "质粒库 & 病毒载体" } }
  ] },
  { cat: "toolCatGenome", tools: [
    { name: "Ensembl", url: "https://ensembl.org/", desc: { en: "Gene annotation & orthologs", zh: "基因注释 & 直系同源" } },
    { name: "UCSC Genome Browser", url: "https://genome.ucsc.edu/", desc: { en: "Genome visualization & track hubs", zh: "基因组可视化 & track hub" } },
    { name: "Enrichr", abbr: "ER", url: "https://maayanlab.cloud/Enrichr/", desc: { en: "Gene set enrichment analysis", zh: "基因集富集分析" } },
    { name: "STRING", url: "https://string-db.org/", desc: { en: "Protein interaction networks", zh: "蛋白相互作用网络" } },
    { name: "DAVID", url: "https://david.ncifcrf.gov/", desc: { en: "GO / KEGG pathway enrichment", zh: "GO / KEGG 通路富集" } },
    { name: "GEO", url: "https://www.ncbi.nlm.nih.gov/geo/", desc: { en: "Public gene expression datasets", zh: "公共基因表达数据集" } }
  ] },
  { cat: "toolCatData", tools: [
    { name: "ImageJ.js", url: "https://ij.imjoy.io/", desc: { en: "Browser-based ImageJ (WASM)", zh: "浏览器版 ImageJ (WASM)" } },
    { name: "BioRender", url: "https://www.biorender.com/", desc: { en: "Scientific figure illustrations", zh: "科学插图绘制" } },
    { name: "protocols.io", url: "https://www.protocols.io/", desc: { en: "Protocol sharing & DOI minting", zh: "实验方案共享 & DOI 注册" } }
  ] },
  { cat: "toolCatCancer", tools: [
    { name: "UCSC Xena Browser", url: "https://xenabrowser.net/", desc: { en: "Multi-omic & clinical data visualization", zh: "多组学及临床数据可视化" } },
    { name: "cBioPortal", url: "https://www.cbioportal.org/", desc: { en: "Cancer genomics datasets explorer", zh: "癌症基因组数据集浏览" } },
    { name: "GDC Data Portal", url: "https://portal.gdc.cancer.gov/", desc: { en: "NCI Genomic Data Commons", zh: "NCI 基因组数据共享平台" } },
    { name: "COSMIC", url: "https://cancer.sanger.ac.uk/cosmic", desc: { en: "Catalogue of somatic mutations in cancer", zh: "癌症体细胞突变目录" } }
  ] },
  { cat: "toolCatStructure", tools: [
    { name: "AlphaFold Protein Structure DB", abbr: "AF", url: "https://alphafold.ebi.ac.uk/", desc: { en: "AI-predicted 3D protein structures", zh: "AI 预测蛋白质三维结构" } },
    { name: "PDB (RCSB)", abbr: "PD", url: "https://www.rcsb.org/", desc: { en: "Protein Data Bank — 3D structures", zh: "蛋白质数据库 — 三维结构" } },
    { name: "Phyre2", url: "http://www.sbg.bio.ic.ac.uk/phyre2/", desc: { en: "Protein structure prediction", zh: "蛋白质结构预测" } },
    { name: "SWISS-MODEL", url: "https://swissmodel.expasy.org/", desc: { en: "Automated homology modelling", zh: "自动化同源建模" } }
  ] },
  { cat: "toolCatPathway", tools: [
    { name: "Reactome", url: "https://reactome.org/", desc: { en: "Curated biological pathway database", zh: "人工审编生物通路数据库" } },
    { name: "KEGG", url: "https://www.genome.jp/kegg/", desc: { en: "Pathway maps & molecular networks", zh: "通路图谱 & 分子网络" } },
    { name: "Cytoscape Web", url: "https://cytoscape.org/", desc: { en: "Network visualization & analysis", zh: "网络可视化 & 分析" } }
  ] },
  { cat: "toolCatClinical", tools: [
    { name: "ClinVar", url: "https://www.ncbi.nlm.nih.gov/clinvar/", desc: { en: "Clinical variant interpretations", zh: "临床变异解读" } },
    { name: "DrugBank", url: "https://go.drugbank.com/", desc: { en: "Drug-target interaction database", zh: "药物-靶标相互作用数据库" } },
    { name: "PharmGKB", url: "https://www.pharmgkb.org/", desc: { en: "Pharmacogenomics knowledge base", zh: "药物基因组学知识库" } }
  ] },
  { cat: "toolCatSingleCell", tools: [
    { name: "CellxGene", url: "https://cellxgene.cziscience.com/", desc: { en: "Single-cell atlas browser", zh: "单细胞图谱浏览器" } },
    { name: "Human Cell Atlas", url: "https://www.humancellatlas.org/", desc: { en: "Reference maps of all human cells", zh: "人类所有细胞的参考图谱" } }
  ] }
];
